nohup: ignoring input
2021-02-22T19:21:03.946-0800 I CONTROL  [initandlisten] MongoDB starting : pid=7331 port=27017 dbpath=data/mongodb 64-bit host=nlp
2021-02-22T19:21:03.946-0800 I CONTROL  [initandlisten] db version v3.6.3
2021-02-22T19:21:03.946-0800 I CONTROL  [initandlisten] git version: 9586e557d54ef70f9ca4b43c26892cd55257e1a5
2021-02-22T19:21:03.946-0800 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
2021-02-22T19:21:03.946-0800 I CONTROL  [initandlisten] allocator: tcmalloc
2021-02-22T19:21:03.946-0800 I CONTROL  [initandlisten] modules: none
2021-02-22T19:21:03.946-0800 I CONTROL  [initandlisten] build environment:
2021-02-22T19:21:03.946-0800 I CONTROL  [initandlisten]     distarch: x86_64
2021-02-22T19:21:03.946-0800 I CONTROL  [initandlisten]     target_arch: x86_64
2021-02-22T19:21:03.946-0800 I CONTROL  [initandlisten] options: { net: { bindIpAll: true }, storage: { dbPath: "data/mongodb", wiredTiger: { engineConfig: { cacheSizeGB: 10.0 } } } }
2021-02-22T19:21:03.946-0800 I -        [initandlisten] Detected data files in data/mongodb created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2021-02-22T19:21:03.946-0800 I STORAGE  [initandlisten] 
2021-02-22T19:21:03.946-0800 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2021-02-22T19:21:03.946-0800 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2021-02-22T19:21:03.946-0800 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=10240M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2021-02-22T19:21:04.628-0800 I STORAGE  [initandlisten] WiredTiger message [1614050464:628692][7331:0x7f547acce0c0], txn-recover: Main recovery loop: starting at 1005/6761856
2021-02-22T19:21:04.723-0800 I STORAGE  [initandlisten] WiredTiger message [1614050464:723616][7331:0x7f547acce0c0], txn-recover: Recovering log 1005 through 1006
2021-02-22T19:21:04.775-0800 I STORAGE  [initandlisten] WiredTiger message [1614050464:775920][7331:0x7f547acce0c0], txn-recover: Recovering log 1006 through 1006
2021-02-22T19:21:04.832-0800 I CONTROL  [initandlisten] 
2021-02-22T19:21:04.832-0800 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2021-02-22T19:21:04.832-0800 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2021-02-22T19:21:04.832-0800 I CONTROL  [initandlisten] 
2021-02-22T19:21:04.833-0800 I CONTROL  [initandlisten] 
2021-02-22T19:21:04.833-0800 I CONTROL  [initandlisten] ** WARNING: You are running on a NUMA machine.
2021-02-22T19:21:04.833-0800 I CONTROL  [initandlisten] **          We suggest launching mongod like this to avoid performance problems:
2021-02-22T19:21:04.833-0800 I CONTROL  [initandlisten] **              numactl --interleave=all mongod [other options]
2021-02-22T19:21:04.833-0800 I CONTROL  [initandlisten] 
2021-02-22T19:21:04.848-0800 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory 'data/mongodb/diagnostic.data'
2021-02-22T19:21:04.849-0800 I NETWORK  [initandlisten] waiting for connections on port 27017
2021-02-22T19:21:10.044-0800 I NETWORK  [listener] connection accepted from 127.0.0.1:48618 #1 (1 connection now open)
2021-02-22T19:21:10.045-0800 I NETWORK  [conn1] received client metadata from 127.0.0.1:48618 conn: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.15.0-135-generic" }, platform: "CPython 3.7.4.final.0" }
2021-02-22T19:21:10.050-0800 I NETWORK  [listener] connection accepted from 127.0.0.1:48620 #2 (2 connections now open)
2021-02-22T19:21:10.051-0800 I NETWORK  [conn2] received client metadata from 127.0.0.1:48620 conn: { driver: { name: "PyMongo", version: "3.10.1" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "4.15.0-135-generic" }, platform: "CPython 3.7.4.final.0" }
2021-02-22T19:22:09.227-0800 I NETWORK  [conn2] end connection 127.0.0.1:48620 (1 connection now open)
2021-02-22T19:22:09.227-0800 I NETWORK  [conn1] end connection 127.0.0.1:48618 (0 connections now open)
2021-02-22T22:14:57.374-0800 I CONTROL  [signalProcessingThread] got signal 1 (Hangup), will terminate after current cmd ends
2021-02-22T22:14:57.374-0800 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2021-02-22T22:14:57.374-0800 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2021-02-22T22:14:57.375-0800 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2021-02-22T22:14:57.382-0800 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2021-02-22T22:14:57.567-0800 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2021-02-22T22:14:57.567-0800 I CONTROL  [signalProcessingThread] now exiting
2021-02-22T22:14:57.567-0800 I CONTROL  [signalProcessingThread] shutting down with code:0
